/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2016-09-18 08:10:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE htm>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-3.1.0.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.leanModal.min.js\"></script> <!--dialog -->\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/layout.css\" type=\"text/css\"> \r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/function.css\" type=\"text/css\"> \r\n");
      out.write("<script>\r\n");
      out.write("$( document ).ready(function() {\r\n");
      out.write("\t/*WebStorge 최근 저장된 로그인정보 가져오기 */\r\n");
      out.write("\tif(!window.localStorage) { \r\n");
      out.write("\t\talert('이 Browser 는 Local Storage 를 지원하지 않습니다.'); \r\n");
      out.write("\t}else { \r\n");
      out.write("\t\t\tvar key = localStorage.key(0); \r\n");
      out.write("\t\t\tvar value = localStorage[key];\r\n");
      out.write("\t\t\t$('#main_loginUserId').val(key);\r\n");
      out.write("\t\t\t$('#main_loginUserPwd').val(value);\r\n");
      out.write("\t};\r\n");
      out.write("\t/* localStorage.clear(); */\r\n");
      out.write("\t\r\n");
      out.write("\t/*로그인 패스워드 확인여부*/\r\n");
      out.write("\t$(\"#main_loginBtn\").click(function(){\r\n");
      out.write("\t\tif ($(\"#main_login_chk\").is(\":checked\")) {\r\n");
      out.write("\t\t\t$.fnWebStorge();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar str = $(\"#loginForm\").serialize();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:'POST',\r\n");
      out.write("\t\t\turl:\"/searchStudy/pwCheck\",\r\n");
      out.write("\t\t\tdata: str,\r\n");
      out.write("\t\t\tsuccess: function(data) {\r\n");
      out.write("\t\t\t\tif(data.result==0){\r\n");
      out.write("\t\t\t\t\t$(\"#main_loginPwCheckArea\").css('display','block');\r\n");
      out.write("\t\t\t\t\t$(\"#main_loginPwCheckArea\").css('background','#ffeeee');\r\n");
      out.write("\t\t\t\t\t$(\"#main_loginPwCheckLabel\").css('color','red');\r\n");
      out.write("\t\t\t\t\t$(\"#main_loginPwCheckLabel\").html(\"이메일 또는 비밀번호를 다시 확인해주세요\");\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t$(\"#main_loginPwCheckArea\").css('display','none');\r\n");
      out.write("\t\t\t\t\t$(\"#loginForm\").submit();\r\n");
      out.write("\t\t\t\t}\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(data) {\r\n");
      out.write("\t\t\t\talert(\"에러\");\r\n");
      out.write("\t\t\t}\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t/*회원가입 아이디 존재여부확인*/\r\n");
      out.write("\tvar joinIdCheck = false;\r\n");
      out.write("\t$(\"#main_joinUserId\").blur(function(){\r\n");
      out.write("\t\tif($(\"#main_joinUserId\").val().length != 0){\r\n");
      out.write("\t\t\tvar str = $(\"#joinForm\").serialize();\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype:'POST',\r\n");
      out.write("\t\t\t\turl:\"/searchStudy/idCheck\",\r\n");
      out.write("\t\t\t\tdata: str,\r\n");
      out.write("\t\t\t\tsuccess: function(data) {\r\n");
      out.write("\t\t\t\t\tvar re = /^(([^<>()[\\]\\\\.,;:\\s@\\\"]+(\\.[^<>()[\\]\\\\.,;:\\s@\\\"]+)*)|(\\\".+\\\"))@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$/;\r\n");
      out.write("\t\t\t\t\tif (re.test($(\"#main_joinUserId\").val())) {\r\n");
      out.write("\t\t\t\t\t\tif(data.result>0){\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#main_joinIdCheckArea\").css('display','block');\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#main_joinIdCheckArea\").css('background','#ffeeee');\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#main_joinIdCheckLabel\").css('color','red');\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#main_joinIdCheckLabel\").html(\"이미 존재하는 이메일 입니다\");\r\n");
      out.write("\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#main_joinIdCheckArea\").css('display','block');\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#main_joinIdCheckArea\").css('background','#def7de');\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#main_joinIdCheckLabel\").css('color','green');\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#main_joinIdCheckLabel\").html(\"사용가능한 이메일입니다\");\r\n");
      out.write("\t\t\t\t\t\t\tjoinIdCheck = true;\r\n");
      out.write("\t\t\t\t\t\t}\t\r\n");
      out.write("\t\t\t\t\t \r\n");
      out.write("\t\t\t\t   return false;\r\n");
      out.write("\t\t\t\t }else{\r\n");
      out.write("\t\t\t\t\t $(\"#main_joinIdCheckArea\").css('display','block');\r\n");
      out.write("\t\t\t\t\t\t$(\"#main_joinIdCheckArea\").css('background','#ffeeee');\r\n");
      out.write("\t\t\t\t\t\t$(\"#main_joinIdCheckLabel\").css('color','red');\r\n");
      out.write("\t\t\t\t\t\t$(\"#main_joinIdCheckLabel\").html(\"올바른 이메일 형식이 아닙니다.\");\r\n");
      out.write("\t\t\t\t }\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror: function(data) {\r\n");
      out.write("\t\t\t\t\talert(\"에러\");\r\n");
      out.write("\t\t\t\t}\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t/*회원가입 비밀번호 사용가능여부확인*/\r\n");
      out.write("\tvar joinPwdCheck= false;\r\n");
      out.write("\t$(\"#main_joinUserPwd\").blur(function(){\r\n");
      out.write("\t\tvar joinPassword = $(\"#main_joinUserPwd\").val();\r\n");
      out.write("\t\tif(joinPassword.length !=0){\r\n");
      out.write("\t\t\tif(joinPassword.length > 0 && joinPassword.length < 8){\r\n");
      out.write("\t\t\t\t$(\"#main_joinPwCheckArea\").css('display','block');\r\n");
      out.write("\t\t\t\t$(\"#main_joinPwCheckArea\").css('background','#ffeeee');\r\n");
      out.write("\t\t\t\t$(\"#main_joinPwCheckLabel\").css('color','red');\r\n");
      out.write("\t\t\t\t$(\"#main_joinPwCheckLabel\").html(\"비밀번호는 8글자이상 입력하시기 바랍니다\");\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t$(\"#main_joinPwCheckArea\").css('display','block');\r\n");
      out.write("\t\t\t\t$(\"#main_joinPwCheckArea\").css('background','#def7de');\r\n");
      out.write("\t\t\t\t$(\"#main_joinPwCheckLabel\").css('color','green');\r\n");
      out.write("\t\t\t\t$(\"#main_joinPwCheckLabel\").html(\"사용가능한 비밀번호 입니다\");\r\n");
      out.write("\t\t\t\tjoinPwdCheck = true;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t/*회원가입 비밀번호 동일여부확인*/\r\n");
      out.write("\tvar joinPwdChkCheck = false;\r\n");
      out.write("\t$(\"#main_joinUserPwdChk\").blur(function(){\r\n");
      out.write("\t\tvar joinPassword = $(\"#main_joinUserPwd\").val();\r\n");
      out.write("\t\tvar joinPasswordChk = $(\"#main_joinUserPwdChk\").val();\r\n");
      out.write("\t\tif(joinPasswordChk.length !=0){\r\n");
      out.write("\t\t\tif(joinPassword != joinPasswordChk ){\r\n");
      out.write("\t\t\t\t$(\"#main_joinPwCheckChkArea\").css('display','block');\r\n");
      out.write("\t\t\t\t$(\"#main_joinPwCheckChkArea\").css('background','#ffeeee');\r\n");
      out.write("\t\t\t\t$(\"#main_joinPwCheckChkLabel\").css('color','red');\r\n");
      out.write("\t\t\t\t$(\"#main_joinPwCheckChkLabel\").html(\"비밀번호가 동일하지 않습니다\");\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t$(\"#main_joinPwCheckChkArea\").css('display','block');\r\n");
      out.write("\t\t\t\t$(\"#main_joinPwCheckChkArea\").css('background','#def7de');\r\n");
      out.write("\t\t\t\t$(\"#main_joinPwCheckChkLabel\").css('color','green');\r\n");
      out.write("\t\t\t\t$(\"#main_joinPwCheckChkLabel\").html(\"비밀번호가 동일합니다\");\r\n");
      out.write("\t\t\t\tjoinPwdChkCheck = true;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t/*회원가입 nickname 동일여부확인*/\r\n");
      out.write("\tvar joinNicknameCheck= false;\r\n");
      out.write("\t$(\"#main_joinUserNickName\").blur(function(){\r\n");
      out.write("\t\tif($(\"#main_joinUserNickName\").val().length != 0){\r\n");
      out.write("\t\t\tvar str = $(\"#joinForm\").serialize();\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype:'POST',\r\n");
      out.write("\t\t\t\turl:\"/searchStudy/nickNameCheck\",\r\n");
      out.write("\t\t\t\tdata: str,\r\n");
      out.write("\t\t\t\tsuccess: function(data) {\r\n");
      out.write("\t\t\t\t\tif(data.result>0){\r\n");
      out.write("\t\t\t\t\t\t$(\"#main_joinNickCheckArea\").css('display','block');\r\n");
      out.write("\t\t\t\t\t\t$(\"#main_joinNickCheckArea\").css('background','#ffeeee');\r\n");
      out.write("\t\t\t\t\t\t$(\"#main_joinNickCheckLabel\").css('color','red');\r\n");
      out.write("\t\t\t\t\t\t$(\"#main_joinNickCheckLabel\").html(\"이미 존재하는 nickname 입니다\");\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t$(\"#main_joinNickCheckArea\").css('display','block');\r\n");
      out.write("\t\t\t\t\t\t$(\"#main_joinNickCheckArea\").css('background','#def7de');\r\n");
      out.write("\t\t\t\t\t\t$(\"#main_joinNickCheckLabel\").css('color','green');\r\n");
      out.write("\t\t\t\t\t\t$(\"#main_joinNickCheckLabel\").html(\"사용가능한 nickname\");\r\n");
      out.write("\t\t\t\t\t\tjoinNicknameCheck =true;\r\n");
      out.write("\t\t\t\t\t}\t\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror: function(data) {\r\n");
      out.write("\t\t\t\t\talert(\"에러\");\r\n");
      out.write("\t\t\t\t}\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t/*회원가입 가능 여부 확인*/\r\n");
      out.write("\t$(\"#main_joinBtn\").click(function(){\r\n");
      out.write("\t\tif(joinIdCheck == true && joinPwdCheck == true && \r\n");
      out.write("\t\t\t\tjoinPwdChkCheck == true && joinNicknameCheck == true){\r\n");
      out.write("\t\t\t$(\"#joinForm\").submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t/*비밀번호 찾기 아이디 존재여부확인*/\r\n");
      out.write("\t$(\"#main_sendEamilBtn\").click(function(){\r\n");
      out.write("\t\tif($(\"#main_pwSearchUser\").val().length != 0){\r\n");
      out.write("\t\t\tvar str = $(\"#pwSearchForm\").serialize();\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype:'POST',\r\n");
      out.write("\t\t\t\turl:\"/searchStudy/idCheck\",\r\n");
      out.write("\t\t\t\tdata: str,\r\n");
      out.write("\t\t\t\tsuccess: function(data) {\r\n");
      out.write("\t\t\t\t\tif(data.result>0){\r\n");
      out.write("\t\t\t\t\t\t$(\"#main_pwSearchCheckArea\").css('display','none');\r\n");
      out.write("\t\t\t\t\t\t$(\"#pwSearchForm\" ).submit();\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t$(\"#main_pwSearchCheckArea\").css('display','block');\r\n");
      out.write("\t\t\t\t\t\t$(\"#main_pwSearchCheckArea\").css('background','#ffeeee');\r\n");
      out.write("\t\t\t\t\t\t$(\"#main_pwSearchCheckLabel\").css('color','red');\r\n");
      out.write("\t\t\t\t\t\t$(\"#main_pwSearchCheckLabel\").html(\"존재하지 않은 이메일 입니다. 다시 확인해주세요\");\r\n");
      out.write("\t\t\t\t\t}\t\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror: function(data) {\r\n");
      out.write("\t\t\t\t\talert(\"에러\");\r\n");
      out.write("\t\t\t\t}\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\t/*********팝업창 관련 jQeury**********/\r\n");
      out.write("\t\t// 로그인 버튼 클릭시\r\n");
      out.write("\t\t$(\".main_loginPopupBtn\").leanModal({\r\n");
      out.write("\t\t\ttop : 100,\r\n");
      out.write("\t\t\toverlay : 0.6,\r\n");
      out.write("\t\t\tcloseButton : \".modal_close\"\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\".main_loginPopupBtn\").click(function() {\r\n");
      out.write("\t\t\t$(\"#main_login\").show();\r\n");
      out.write("\t\t\t$(\"#main_join\").hide();\r\n");
      out.write("\t\t\t$(\"#main_pwSearch\").hide();\r\n");
      out.write("\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t// 회원가입 버튼 클릭시\r\n");
      out.write("\t\t$(\".main_joinPopupBtn\").leanModal({\r\n");
      out.write("\t\t\ttop : 100,\r\n");
      out.write("\t\t\toverlay : 0.6,\r\n");
      out.write("\t\t\tcloseButton : \".modal_close\"\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t$(\".main_joinPopupBtn\").click(function() {\r\n");
      out.write("\t\t\t$(\"#main_join\").show();\r\n");
      out.write("\t\t\t$(\"#main_login\").hide();\r\n");
      out.write("\t\t\t$(\"#main_pwSearch\").hide();\r\n");
      out.write("\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 비밀번호찾기 버튼 클릭시\r\n");
      out.write("\t\t$(\".main_pwSearchBtn\").leanModal({\r\n");
      out.write("\t\t\ttop : 100,\r\n");
      out.write("\t\t\toverlay : 0.6,\r\n");
      out.write("\t\t\tcloseButton : \".modal_close\"\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t$(\".main_pwSearchBtn\").click(function() {\r\n");
      out.write("\t\t\t$(\"#main_pwSearch\").show();\r\n");
      out.write("\t\t\t$(\"#main_login\").hide();\r\n");
      out.write("\t\t\t$(\"#main_join\").hide();\r\n");
      out.write("\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 주변 화면으로 팝업 종료 */\r\n");
      out.write("\t\t$(\"#lean_overlay\").click(function(){\r\n");
      out.write("\t\t\t$(\"#main_loginWrap input[type=text]\").val(\"\");\r\n");
      out.write("\t\t\t$(\".main_labelRow\").css(\"display\",\"none\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<a class=\"main_loginPopupBtn\" href=\"#main_loginModal\">로그인</a>\r\n");
      out.write("\t\t<a class=\"main_joinPopupBtn\" href=\"#main_joinModal\">회원가입</a>\r\n");
      out.write("\t\t<div id=\"main_loginWrap\">\r\n");
      out.write("\t\t\t<div id=\"main_loginModal\" class=\"main_loginPopup\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t<!-- 로그인 페이지-->\r\n");
      out.write("\t\t\t\t<div id=\"main_login\">\r\n");
      out.write("\t\t\t\t\t<div id=\"main_loginHeader\">\r\n");
      out.write("\t\t\t\t\t\t<h1>SEARCH STUDY</h1>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<form action=\"login\" method=\"post\" id=\"loginForm\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"main_inputRow\" id=\"main_loginIdArea\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"email\" placeholder=\"이메일\" id=\"main_loginUserId\" name=\"main_loginUserId\" class=\"inputBox1\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"main_labelRow\"  id=\"main_loginIdCheckArea\" style=\"display:none\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"main_loginCheck\" id=\"main_loginIdCheckLabel\"> </label>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"main_inputRow\" id=\"main_passwordArea\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" placeholder=\"비밀번호\" id=\"main_loginUserPwd\" name=\"main_loginUserPwd\" class=\"inputBox1\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"main_labelRow\"  id=\"main_loginPwCheckArea\" style=\"display:none\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"main_loginCheck\" id=\"main_loginPwCheckLabel\"> 패스워드를 다시 확인해주세요</label>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"main_loginBtn_area\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"button\" value=\"로그인\" id=\"main_loginBtn\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"main_sendLoginBtn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" id=\"main_login_chk\" value=\"off\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>로그인 상태 저장</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t<div id=\"main_find_info\">\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <a href=\"#\"> 아이디 찾기</a> <span>|</span> -->\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#main_pwSearchModal\" class=\"main_pwSearchBtn\"> 비밀번호 찾기</a> <span>|</span>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#main_joinModal\" class=\"main_joinPopupBtn\"> 회원가입</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"main_joinModal\" class=\"main_joinPopup\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t<!-- 회원가입 페이지-->\r\n");
      out.write("\t\t\t\t<div id=\"main_join\" >\r\n");
      out.write("\t\t\t\t\t<div id=\"main_joinHeader\">\r\n");
      out.write("\t\t\t\t\t\t<h1>SEARCH STUDY</h1>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<form action=\"mjoin\" method=\"post\" id=\"joinForm\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"main_joinIdArea\" class=\"divBox1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"email\" placeholder=\"이메일\" class=\"inputBox1\" name=\"main_joinUserId\" id=\"main_joinUserId\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"main_labelRow\"  id=\"main_joinIdCheckArea\" style=\"display:none\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"main_loginCheck\" id=\"main_joinIdCheckLabel\"> </label>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"main_joinPwArea\" class=\"divBox1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" placeholder=\"비밀번호\" class=\"inputBox1\" name=\"main_joinUserPwd\" id=\"main_joinUserPwd\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"main_labelRow\"  id=\"main_joinPwCheckArea\" style=\"display:none\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"main_loginCheck\" id=\"main_joinPwCheckLabel\"> </label>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"main_joinPwcheckArea\" class=\"divBox1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" placeholder=\"비밀번호확인\" class=\"inputBox1\" name=\"main_joinUserPwdChk\" id=\"main_joinUserPwdChk\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"main_labelRow\"  id=\"main_joinPwCheckChkArea\" style=\"display:none\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"main_loginCheck\" id=\"main_joinPwCheckChkLabel\"> </label>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"main_joinNickArea\" class=\"divBox1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" placeholder=\"닉네임\" class=\"inputBox1\" name=\"main_joinUserNickName\" id=\"main_joinUserNickName\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"main_labelRow\"  id=\"main_joinNickCheckArea\" style=\"display:none\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"main_loginCheck\" id=\"main_joinNickCheckLabel\"> </label>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"main_sendInfoBtn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"button\" value=\"가입하기\" id=\"main_joinBtn\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"main_backArea\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#main_loginModal\" class=\"main_loginPopupBtn\"> 로그인</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"main_pwSearchModal\" class=\"main_pwSearchPopup\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t<!-- 비밀번호찾기 페이지-->\r\n");
      out.write("\t\t\t\t<div id=\"main_pwSearch\" >\r\n");
      out.write("\t\t\t\t\t<div id=\"main_pwSearchHeader\">\r\n");
      out.write("\t\t\t\t\t\t<h1>SEARCH STUDY</h1>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<form action=\"sendEmail\" method=\"post\" id=\"pwSearchForm\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"main_pwSearchArea\" class=\"divBox1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" placeholder=\"이메일\" class=\"inputBox1\" name=\"main_pwSearchUser\" id=\"main_pwSearchUser\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"main_labelRow\"  id=\"main_pwSearchCheckArea\" style=\"display:none\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"main_loginCheck\" id=\"main_pwSearchCheckLabel\"> </label>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"main_sendEamilBtn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"button\" value=\"이메일로 보내기\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"main_backArea\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#main_loginModal\" class=\"main_loginPopupBtn\"> 로그인</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
