/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.30
 * Generated at: 2016-09-27 00:12:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.Member;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
 Member member = (Member)session.getAttribute("member"); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"css/main.css\" type=\"text/css\"/>\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"css/layout.css\" type=\"text/css\">  \r\n");
      out.write(" <link rel=\"stylesheet\" href=\"css/function.css\" type=\"text/css\"> \r\n");
      out.write(" <script type=\"text/javascript\" src=\"js/jquery-3.1.0.min.js\"> </script>\r\n");
      out.write(" <script type=\"text/javascript\" src=\"js/navigation.js\"> </script>\r\n");
      out.write(" <script type=\"text/javascript\" src=\"js/jquery.leanModal.min.js\"></script> <!--dialog -->\r\n");
      out.write("<title>main</title>\r\n");
      out.write("<script>\r\n");
      out.write("$( document ).ready(function() {\r\n");
      out.write("\t   $(\"button\").attr(\"tabindex\", \"-1\");\r\n");
      out.write("\t   $(\"body\").on(\"click\", \" button\", function(e)\r\n");
      out.write("\t   {\r\n");
      out.write("\t      var type = $(this).data(\"type\");\r\n");
      out.write("\r\n");
      out.write("\t      if(type != null)\r\n");
      out.write("\t      {\r\n");
      out.write("\t         $(this).blur();\r\n");
      out.write("\t         $.proxy(eval(type), this)();\r\n");
      out.write("\t      }\r\n");
      out.write("\t   });\r\n");
      out.write("\t   $(\"#banner\").on(\"selectstart\", function()\r\n");
      out.write("\t         {\r\n");
      out.write("\t             return false;\r\n");
      out.write("\t         });\r\n");
      out.write("\t$(\"#banner\").on(\"selectstart\", function()\r\n");
      out.write("\t      {\r\n");
      out.write("\t          return false;\r\n");
      out.write("\t      });\r\n");
      out.write("\t      function TriSlider(options) {\r\n");
      out.write("\t          var slider = $(options.selector);\r\n");
      out.write("\t          var pieces = slider.children(\".pieces\");\r\n");
      out.write("\t          var max = pieces.data('max');\r\n");
      out.write("\t          var fake_pieces = options.fake_pieces? options.fake_pieces:2;\r\n");
      out.write("\t          var width = 850;\r\n");
      out.write("\t          var start_point = -width * (fake_pieces-1);\r\n");
      out.write("\t          var start_index = options.start_index? options.start_index:0;\r\n");
      out.write("\t          var isSliding = false;\r\n");
      out.write("\r\n");
      out.write("\t          (function() {\r\n");
      out.write("\t              pieces.data('index', start_index);\r\n");
      out.write("\t              pieces.css('left', (-width*(start_index+1) + start_point)+'px');\r\n");
      out.write("\t          \r\n");
      out.write("\t              slider.find(\".index>li\").removeClass('current');\r\n");
      out.write("\t              slider.find(\".index>li[data-id=\"+start_index+\"]\").addClass('current');\r\n");
      out.write("\r\n");
      out.write("\t              pieces.show();\r\n");
      out.write("\t          })();\r\n");
      out.write("\r\n");
      out.write("\t          var piece = slider.find(\".piece\"),\r\n");
      out.write("\t              first   = piece.filter(':first'),\r\n");
      out.write("\t              last    = piece.filter(':last');\r\n");
      out.write("\r\n");
      out.write("\t          // 슬라이더가 0개임\r\n");
      out.write("\t          if(piece.length == 0) \r\n");
      out.write("\t              return false;\r\n");
      out.write("\r\n");
      out.write("\t          // 가짜 페이지들을 만들 때, 설정한 갯수가 진짜 페이지의 최대 갯수보다 많을 경우\r\n");
      out.write("\t          var rest = fake_pieces % piece.length;\r\n");
      out.write("\t          if(rest > 0) {\r\n");
      out.write("\t              first.before( piece.slice(-1 * rest).clone(true) );\r\n");
      out.write("\t              last.after( piece.slice(0, rest).clone(true) );\r\n");
      out.write("\t          }\r\n");
      out.write("\r\n");
      out.write("\t          for(var i=0, len = Math.floor(fake_pieces / piece.length); i<len; ++i) {\r\n");
      out.write("\t              first.before( piece.clone(true) );\r\n");
      out.write("\t              last.after( piece.clone(true) );\r\n");
      out.write("\t          }\r\n");
      out.write("\r\n");
      out.write("\t          var slide = function(add) {\r\n");
      out.write("\t              isSliding = true;\r\n");
      out.write("\t              var index = pieces.data('index');\r\n");
      out.write("\r\n");
      out.write("\t              index += add;\r\n");
      out.write("\t              pieces.data('index', index);\r\n");
      out.write("\t              pieces.animate({left : (-width*(index+1) + start_point)+'px'}, \r\n");
      out.write("\t                  {'duration':300,\r\n");
      out.write("\t                   'complete':function() {\r\n");
      out.write("\t                      if(index == -1) { // attach to left\r\n");
      out.write("\t                          index = max - 1;\r\n");
      out.write("\t                          pieces.data('index', index);\r\n");
      out.write("\t                          pieces.css('left', (-width*(index+1) + start_point)+'px');\r\n");
      out.write("\t                      } else if(index == max) { // attach to right\r\n");
      out.write("\t                          index = 0;\r\n");
      out.write("\t                          pieces.data('index', index);\r\n");
      out.write("\t                          pieces.css('left', (-width*(index+1) + start_point)+'px');\r\n");
      out.write("\t                      }\r\n");
      out.write("\t                      slider.find(\".index>li\").removeClass('current');\r\n");
      out.write("\t                      slider.find(\".index>li[data-id=\"+index+\"]\").addClass('current');\r\n");
      out.write("\r\n");
      out.write("\t                      if( options.complete )\r\n");
      out.write("\t                          options.complete( pieces.children(\".piece\").get(index+fake_pieces) );\r\n");
      out.write("\r\n");
      out.write("\t                      isSliding = false;\r\n");
      out.write("\t                  }\r\n");
      out.write("\t              });\r\n");
      out.write("\t          }\r\n");
      out.write("\r\n");
      out.write("\t          this.prev = function() {\r\n");
      out.write("\t              if(isSliding === false)\r\n");
      out.write("\t                  slide(-1);\r\n");
      out.write("\t          };\r\n");
      out.write("\r\n");
      out.write("\t          this.next = function() {\r\n");
      out.write("\t              if(isSliding === false)\r\n");
      out.write("\t                  slide(1);\r\n");
      out.write("\t          };\r\n");
      out.write("\t          \r\n");
      out.write("\t          slider.find(\".nav>.left\").click(this.prev);\r\n");
      out.write("\t          slider.find(\".nav>.right\").click(this.next);\r\n");
      out.write("\r\n");
      out.write("\t          if(options.duration > 0)\r\n");
      out.write("\t              setInterval(this.next, options.duration);\r\n");
      out.write("\t      };\r\n");
      out.write("\t      var TriSlider = new TriSlider({'selector':'#banner>.trislider'});\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("$( document ).ready(function() {\r\n");
      out.write("\t/*WebStorge 최근 저장된 로그인정보 가져오기 */\r\n");
      out.write("\tif(!window.localStorage) { \r\n");
      out.write("\t\talert('이 Browser 는 Local Storage 를 지원하지 않습니다.'); \r\n");
      out.write("\t}else { \r\n");
      out.write("\t\t\tvar key = localStorage.key(0); \r\n");
      out.write("\t\t\tvar value = localStorage[key];\r\n");
      out.write("\t\t\t$('#main_loginUserId').val(key);\r\n");
      out.write("\t\t\t$('#main_loginUserPwd').val(value);\r\n");
      out.write("\t};\r\n");
      out.write("\t/* localStorage.clear(); */\r\n");
      out.write("\t\r\n");
      out.write("\t/*로그인 패스워드 확인여부*/\r\n");
      out.write("\t$(\"#main_loginBtn\").click(function(){\r\n");
      out.write("\t\t\talert(\"\");\r\n");
      out.write("\t\tif ($(\"#main_login_chk\").is(\":checked\")) {\r\n");
      out.write("\t\t\t$.fnWebStorge();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar str = $(\"#loginForm\").serialize();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:'POST',\r\n");
      out.write("\t\t\turl:\"/easyStudy/pwCheck\",\r\n");
      out.write("\t\t\tdata: str,\r\n");
      out.write("\t\t\tsuccess: function(data) {\r\n");
      out.write("\t\t\t\tif(data.result==0){\r\n");
      out.write("\t\t\t\t\t$(\"#main_loginPwCheckArea\").css('display','block');\r\n");
      out.write("\t\t\t\t\t$(\"#main_loginPwCheckArea\").css('background','#ffeeee');\r\n");
      out.write("\t\t\t\t\t$(\"#main_loginPwCheckLabel\").css('color','red');\r\n");
      out.write("\t\t\t\t\t$(\"#main_loginPwCheckLabel\").html(\"이메일 또는 비밀번호를 다시 확인해주세요\");\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t$(\"#main_loginPwCheckArea\").css('display','none');\r\n");
      out.write("\t\t\t\t\t$(\"#loginForm\").submit();\r\n");
      out.write("\t\t\t\t}\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(data) {\r\n");
      out.write("\t\t\t\talert(\"에러\");\r\n");
      out.write("\t\t\t}\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t/*회원가입 아이디 존재여부확인*/\r\n");
      out.write("\tvar joinIdCheck = false;\r\n");
      out.write("\t$(\"#main_joinUserId\").blur(function(){\r\n");
      out.write("\t\tif($(\"#main_joinUserId\").val().length != 0){\r\n");
      out.write("\t\t\tvar str = $(\"#joinForm\").serialize();\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype:'POST',\r\n");
      out.write("\t\t\t\turl:\"/easyStudy/idCheck\",\r\n");
      out.write("\t\t\t\tdata: str,\r\n");
      out.write("\t\t\t\tsuccess: function(data) {\r\n");
      out.write("\t\t\t\t\tvar re = /^(([^<>()[\\]\\\\.,;:\\s@\\\"]+(\\.[^<>()[\\]\\\\.,;:\\s@\\\"]+)*)|(\\\".+\\\"))@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$/;\r\n");
      out.write("\t\t\t\t\tif (re.test($(\"#main_joinUserId\").val())) {\r\n");
      out.write("\t\t\t\t\t\tif(data.result>0){\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#main_joinIdCheckArea\").css('display','block');\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#main_joinIdCheckArea\").css('background','#ffeeee');\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#main_joinIdCheckLabel\").css('color','red');\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#main_joinIdCheckLabel\").html(\"이미 존재하는 이메일 입니다\");\r\n");
      out.write("\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#main_joinIdCheckArea\").css('display','block');\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#main_joinIdCheckArea\").css('background','#def7de');\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#main_joinIdCheckLabel\").css('color','green');\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#main_joinIdCheckLabel\").html(\"사용가능한 이메일입니다\");\r\n");
      out.write("\t\t\t\t\t\t\tjoinIdCheck = true;\r\n");
      out.write("\t\t\t\t\t\t}\t\r\n");
      out.write("\t\t\t\t\t \r\n");
      out.write("\t\t\t\t   return false;\r\n");
      out.write("\t\t\t\t }else{\r\n");
      out.write("\t\t\t\t\t $(\"#main_joinIdCheckArea\").css('display','block');\r\n");
      out.write("\t\t\t\t\t\t$(\"#main_joinIdCheckArea\").css('background','#ffeeee');\r\n");
      out.write("\t\t\t\t\t\t$(\"#main_joinIdCheckLabel\").css('color','red');\r\n");
      out.write("\t\t\t\t\t\t$(\"#main_joinIdCheckLabel\").html(\"올바른 이메일 형식이 아닙니다.\");\r\n");
      out.write("\t\t\t\t }\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror: function(data) {\r\n");
      out.write("\t\t\t\t\talert(\"에러\");\r\n");
      out.write("\t\t\t\t}\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t/*회원가입 비밀번호 사용가능여부확인*/\r\n");
      out.write("\tvar joinPwdCheck= false;\r\n");
      out.write("\t$(\"#main_joinUserPwd\").blur(function(){\r\n");
      out.write("\t\tvar joinPassword = $(\"#main_joinUserPwd\").val();\r\n");
      out.write("\t\tif(joinPassword.length !=0){\r\n");
      out.write("\t\t\tif(joinPassword.length > 0 && joinPassword.length < 8){\r\n");
      out.write("\t\t\t\t$(\"#main_joinPwCheckArea\").css('display','block');\r\n");
      out.write("\t\t\t\t$(\"#main_joinPwCheckArea\").css('background','#ffeeee');\r\n");
      out.write("\t\t\t\t$(\"#main_joinPwCheckLabel\").css('color','red');\r\n");
      out.write("\t\t\t\t$(\"#main_joinPwCheckLabel\").html(\"비밀번호는 8글자이상 입력하시기 바랍니다\");\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t$(\"#main_joinPwCheckArea\").css('display','block');\r\n");
      out.write("\t\t\t\t$(\"#main_joinPwCheckArea\").css('background','#def7de');\r\n");
      out.write("\t\t\t\t$(\"#main_joinPwCheckLabel\").css('color','green');\r\n");
      out.write("\t\t\t\t$(\"#main_joinPwCheckLabel\").html(\"사용가능한 비밀번호 입니다\");\r\n");
      out.write("\t\t\t\tjoinPwdCheck = true;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t/*회원가입 비밀번호 동일여부확인*/\r\n");
      out.write("\tvar joinPwdChkCheck = false;\r\n");
      out.write("\t$(\"#main_joinUserPwdChk\").blur(function(){\r\n");
      out.write("\t\tvar joinPassword = $(\"#main_joinUserPwd\").val();\r\n");
      out.write("\t\tvar joinPasswordChk = $(\"#main_joinUserPwdChk\").val();\r\n");
      out.write("\t\tif(joinPasswordChk.length !=0){\r\n");
      out.write("\t\t\tif(joinPassword != joinPasswordChk ){\r\n");
      out.write("\t\t\t\t$(\"#main_joinPwCheckChkArea\").css('display','block');\r\n");
      out.write("\t\t\t\t$(\"#main_joinPwCheckChkArea\").css('background','#ffeeee');\r\n");
      out.write("\t\t\t\t$(\"#main_joinPwCheckChkLabel\").css('color','red');\r\n");
      out.write("\t\t\t\t$(\"#main_joinPwCheckChkLabel\").html(\"비밀번호가 동일하지 않습니다\");\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t$(\"#main_joinPwCheckChkArea\").css('display','block');\r\n");
      out.write("\t\t\t\t$(\"#main_joinPwCheckChkArea\").css('background','#def7de');\r\n");
      out.write("\t\t\t\t$(\"#main_joinPwCheckChkLabel\").css('color','green');\r\n");
      out.write("\t\t\t\t$(\"#main_joinPwCheckChkLabel\").html(\"비밀번호가 동일합니다\");\r\n");
      out.write("\t\t\t\tjoinPwdChkCheck = true;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t/*회원가입 nickname 동일여부확인*/\r\n");
      out.write("\tvar joinNicknameCheck= false;\r\n");
      out.write("\t$(\"#main_joinUserNickName\").blur(function(){\r\n");
      out.write("\t\tif($(\"#main_joinUserNickName\").val().length != 0){\r\n");
      out.write("\t\t\tvar str = $(\"#joinForm\").serialize();\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype:'POST',\r\n");
      out.write("\t\t\t\turl:\"/easyStudy/nickNameCheck\",\r\n");
      out.write("\t\t\t\tdata: str,\r\n");
      out.write("\t\t\t\tsuccess: function(data) {\r\n");
      out.write("\t\t\t\t\tif(data.result>0){\r\n");
      out.write("\t\t\t\t\t\t$(\"#main_joinNickCheckArea\").css('display','block');\r\n");
      out.write("\t\t\t\t\t\t$(\"#main_joinNickCheckArea\").css('background','#ffeeee');\r\n");
      out.write("\t\t\t\t\t\t$(\"#main_joinNickCheckLabel\").css('color','red');\r\n");
      out.write("\t\t\t\t\t\t$(\"#main_joinNickCheckLabel\").html(\"이미 존재하는 nickname 입니다\");\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t$(\"#main_joinNickCheckArea\").css('display','block');\r\n");
      out.write("\t\t\t\t\t\t$(\"#main_joinNickCheckArea\").css('background','#def7de');\r\n");
      out.write("\t\t\t\t\t\t$(\"#main_joinNickCheckLabel\").css('color','green');\r\n");
      out.write("\t\t\t\t\t\t$(\"#main_joinNickCheckLabel\").html(\"사용가능한 nickname\");\r\n");
      out.write("\t\t\t\t\t\tjoinNicknameCheck =true;\r\n");
      out.write("\t\t\t\t\t}\t\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror: function(data) {\r\n");
      out.write("\t\t\t\t\talert(\"에러\");\r\n");
      out.write("\t\t\t\t}\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t/*회원가입 가능 여부 확인*/\r\n");
      out.write("\t$(\"#main_joinBtn\").click(function(){\r\n");
      out.write("\t\tif(joinIdCheck == true && joinPwdCheck == true && \r\n");
      out.write("\t\t\t\tjoinPwdChkCheck == true && joinNicknameCheck == true){\r\n");
      out.write("\t\t\t$(\"#joinForm\").submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t/*비밀번호 찾기 아이디 존재여부확인*/\r\n");
      out.write("\t$(\"#main_sendEamilBtn\").click(function(){\r\n");
      out.write("\t\tif($(\"#main_pwSearchUser\").val().length != 0){\r\n");
      out.write("\t\t\tvar str = $(\"#pwSearchForm\").serialize();\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype:'POST',\r\n");
      out.write("\t\t\t\turl:\"/easyStudy/idCheck\",\r\n");
      out.write("\t\t\t\tdata: str,\r\n");
      out.write("\t\t\t\tsuccess: function(data) {\r\n");
      out.write("\t\t\t\t\tif(data.result>0){\r\n");
      out.write("\t\t\t\t\t\t$(\"#main_pwSearchCheckArea\").css('display','none');\r\n");
      out.write("\t\t\t\t\t\t$(\"#pwSearchForm\" ).submit();\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t$(\"#main_pwSearchCheckArea\").css('display','block');\r\n");
      out.write("\t\t\t\t\t\t$(\"#main_pwSearchCheckArea\").css('background','#ffeeee');\r\n");
      out.write("\t\t\t\t\t\t$(\"#main_pwSearchCheckLabel\").css('color','red');\r\n");
      out.write("\t\t\t\t\t\t$(\"#main_pwSearchCheckLabel\").html(\"존재하지 않은 이메일 입니다. 다시 확인해주세요\");\r\n");
      out.write("\t\t\t\t\t}\t\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror: function(data) {\r\n");
      out.write("\t\t\t\t\talert(\"에러\");\r\n");
      out.write("\t\t\t\t}\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\t/*********팝업창 관련 jQeury**********/\r\n");
      out.write("\t\t// 로그인 버튼 클릭시\r\n");
      out.write("\t\t$(\".main_loginPopupBtn\").leanModal({\r\n");
      out.write("\t\t\ttop : 100,\r\n");
      out.write("\t\t\toverlay : 0.6,\r\n");
      out.write("\t\t\tcloseButton : \".modal_close\"\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\".main_loginPopupBtn\").click(function() {\r\n");
      out.write("\t\t\t$(\"#main_login\").show();\r\n");
      out.write("\t\t\t$(\"#main_join\").hide();\r\n");
      out.write("\t\t\t$(\"#main_pwSearch\").hide();\r\n");
      out.write("\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t// 회원가입 버튼 클릭시\r\n");
      out.write("\t\t$(\".main_joinPopupBtn\").leanModal({\r\n");
      out.write("\t\t\ttop : 100,\r\n");
      out.write("\t\t\toverlay : 0.6,\r\n");
      out.write("\t\t\tcloseButton : \".modal_close\"\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t$(\".main_joinPopupBtn\").click(function() {\r\n");
      out.write("\t\t\t$(\"#main_join\").show();\r\n");
      out.write("\t\t\t$(\"#main_login\").hide();\r\n");
      out.write("\t\t\t$(\"#main_pwSearch\").hide();\r\n");
      out.write("\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 비밀번호찾기 버튼 클릭시\r\n");
      out.write("\t\t$(\".main_pwSearchBtn\").leanModal({\r\n");
      out.write("\t\t\ttop : 100,\r\n");
      out.write("\t\t\toverlay : 0.6,\r\n");
      out.write("\t\t\tcloseButton : \".modal_close\"\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t$(\".main_pwSearchBtn\").click(function() {\r\n");
      out.write("\t\t\t$(\"#main_pwSearch\").show();\r\n");
      out.write("\t\t\t$(\"#main_login\").hide();\r\n");
      out.write("\t\t\t$(\"#main_join\").hide();\r\n");
      out.write("\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 주변 화면으로 팝업 종료 */\r\n");
      out.write("\t\t$(\"#lean_overlay\").click(function(){\r\n");
      out.write("\t\t\t$(\"#main_loginWrap input[type=text]\").val(\"\");\r\n");
      out.write("\t\t\t$(\"#main_loginWrap input[type=email]\").val(\"\");\r\n");
      out.write("\t\t\t$(\"#main_loginWrap input[type=password]\").val(\"\");\r\n");
      out.write("\t\t\t$(\"#main_loginWrap input[type=checkbox]\").prop('checked', false);\r\n");
      out.write("\t\t\t$(\".main_labelRow\").css(\"display\",\"none\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"wrap\">\r\n");
      out.write("\t<div id=\"header\">\r\n");
      out.write("\t\t<div id=\"nav_warp_shading\"></div>\r\n");
      out.write("\t\t<div id=\"nav_wrap\" class=\"fixed\">\r\n");
      out.write("\t<div class=\"container_wrap\">\r\n");
      out.write("\t<form action=\"/easyStudy/search.store\" method=\"get\">\r\n");
      out.write("\t\t<div id=\"nav_container\" class=\"\">\r\n");
      out.write("\t\t\t<div id=\"nav_shading\" class=\"shading_bg\" style=\"display: none;\"></div>\r\n");
      out.write("\t\t\t\t<!-- logo section -->\r\n");
      out.write("\t\t\t<a id=\"nav_logo\" href=\"index.jsp\"><img class=\"logo\" src=\"images/logo.png\"></a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- area search section -->\r\n");
      out.write("\t\t\t<div id=\"nav_area\" class=\"search sel\">\r\n");
      out.write("\t\t\t\t<div class=\"input\">\r\n");
      out.write("\t\t\t\t\t<div class=\"selected\">지역 선택 </div>\r\n");
      out.write("\t\t\t\t\t<img src=\"images/down_arrow.png\" class=\"searchbox arrow\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"box\" id=\"box1\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"district content\">\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\" name=\"area\" id=\"GN\" value=\"GN\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"GN\">강남</label>\r\n");
      out.write("    \t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><input type=\"checkbox\" name=\"area\" id=\"JL\" value=\"JL\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"JL\">종로</label></li>\r\n");
      out.write("\t\t\t\t\t\t<li><input type=\"checkbox\" name=\"area\" id=\"SC\" value=\"SC\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"SC\">신촌</label></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<!--<button type=\"button\" id=\"off\" class=\"confirm red_fill border_radius soft\">확인</button>-->\r\n");
      out.write("\t\t\t\t\t<button class=\"confirm red_fill border_radius soft\" type=\"button\">확인</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- genre search section -->\r\n");
      out.write("\t\t\t<div id=\"nav_genre\" class=\"search sel\">\r\n");
      out.write("\t\t\t\t<div class=\"input\">\r\n");
      out.write("\t\t\t\t\t<div class=\"selected\">카테고리 선택</div>\r\n");
      out.write("\t\t\t\t\t<img src=\"images/down_arrow.png\" class=\"searchbox arrow\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"box\" id=\"box2\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"search_category content\">\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\" name=\"category\" id=\"S10\" value=\"S10\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"S10\">도서관/독서실</label>\r\n");
      out.write("    \t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><input type=\"checkbox\" name=\"category\" id=\"S20\" value=\"S20\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"S20\">스터디룸</label></li>\r\n");
      out.write("\t\t\t\t\t\t<li><input type=\"checkbox\" name=\"category\" id=\"S30\" value=\"S30\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"S30\">스터디카페</label></li>\r\n");
      out.write("\t\t\t\t\t\t<!--  <li><input type=\"checkbox\" name=\"category\" id=\"S40\" value=\"S40\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"S40\">스터디룸/스터디카페</label></li>-->\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<button class=\"confirm red_fill border_radius soft\" type=\"button\">확인</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<button type=\"submit\" id=\"nav_btn\" class=\"search\">검색</button>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<!-- account section -->\r\n");
      out.write("\t\t\t\t<div id=\"nav_account\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"nav_guest\">\r\n");
      out.write("\t\t\t\t\t\t");
if(member !=null){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<span id=\"nav_login\" ><a class=\"main_loginPopupBtn\" href=\"/easyStudy/logout\">로그아웃</a></span>\r\n");
      out.write("\t\t\t\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<span id=\"nav_login\" ><a class=\"main_loginPopupBtn\" href=\"#main_loginModal\">로그인</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;|&nbsp;\r\n");
      out.write("\t\t\t\t\t\t");
} 
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t<span id=\"nav_join\"><a class=\"main_joinPopupBtn\" href=\"#main_joinModal\">회원가입</a></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t<div class=\"menu_wrap\">\r\n");
      out.write("\t\t\t<div id=\"nav_menu\">\r\n");
      out.write("\t\t\t<!-- \t <a href=\"#\" class=\"underline \">메뉴</a>\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"underline \">메뉴</a>\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"underline \">메뉴</a>\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"underline \">메뉴<i class=\"text new\"></i></a> -->\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t");
 if(member != null){
					if("admin".equals(member.getUserId())) { 
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(member.getNickName() );
      out.write("님  &nbsp; &nbsp; &nbsp;\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/easyStudy/mmanagement?page=1\">회원 관리</a> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">글쓰기</a>\t\t\r\n");
      out.write("\t\t\t\t\t");
}else{ 
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(member.getNickName() );
      out.write("님  &nbsp; &nbsp; &nbsp;\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/easyStudy/mbookmark?userid=");
      out.print(member.getUserId() );
      out.write("\">즐겨찾기</a> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/easyStudy/mreview?page=1&nickname=");
      out.print(member.getNickName() );
      out.write("\">내가 쓴 리뷰</a> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/easyStudy/mypage/myinfo.jsp\">내 정보 변경</a> \t\t\r\n");
      out.write("\t\t\t\t\t");
}
				}else{} 
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--<div class=\"menu_wrap\">\r\n");
      out.write("\t\t\t<div id=\"nav_menu\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t</div>-->\r\n");
      out.write("\t<div id=\"container\">\r\n");
      out.write("\t\t<!--배너 슬라이더 이미지 banner_warp-->\r\n");
      out.write("\t\t<div id=\"banner_wrap\">\r\n");
      out.write("   \r\n");
      out.write("<div id=\"banner\">\r\n");
      out.write("    <div class=\"trislider\">\r\n");
      out.write("       <div class=\"pieces\" data-index=\"0\" data-max=\"5\" style=\"left: -1700px; display: block;\">\r\n");
      out.write("                       <a href=\"\" class=\"piece\" style=\"background-image:url(images/main1.jpg);\"></a>\r\n");
      out.write("                       <a href=\"\" class=\"piece\" style=\"background-image:url(images/main2.jpg)\"></a>\r\n");
      out.write("                       <a href=\"\" class=\"piece\" style=\"background-image:url(images/main3.jpg)\"></a>\r\n");
      out.write("                       <a href=\"\" class=\"piece\" style=\"background-image:url(images/main4.jpg)\"></a>\r\n");
      out.write("                       <a href=\"\" class=\"piece\" style=\"background-image:url(images/main5.jpg)\"></a>\r\n");
      out.write("                    \r\n");
      out.write("                 </div>\r\n");
      out.write("      <div class=\"left shadow\"></div>\r\n");
      out.write("        <div class=\"right shadow\"></div>\r\n");
      out.write("        \r\n");
      out.write("        <ul class=\"index\">\r\n");
      out.write("                         <li data-id=\"0\" class=\"current\">●</li>\r\n");
      out.write("                         <li data-id=\"1\" class=\"\">●</li>\r\n");
      out.write("                         <li data-id=\"2\" class=\"\">●</li>\r\n");
      out.write("                         <li data-id=\"3\" class=\"\">●</li>\r\n");
      out.write("                         <li data-id=\"4\" class=\"\">●</li>\r\n");
      out.write("                   </ul> \r\n");
      out.write("       <div class=\"nav\">\r\n");
      out.write("        \t\t\t<img class=\"left\" alt=\"icon\" src=\"images/left_arrow.png\" />\r\n");
      out.write("        \t\t\t<img class=\"right\" alt=\"icon\" src=\"images/right_arrow.png\"/>\r\n");
      out.write("       \t\t\t</div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div></div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!--배너 슬라이더 이미지 banner_warp-->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!--쉬운 카테고리 선택 content_warp -->\r\n");
      out.write("\t\t<div id=\"content_wrap\">\r\n");
      out.write("\t\t\t<div class=\"section\">\r\n");
      out.write("    \t\t\t<div class=\"title\">지역별</div>\r\n");
      out.write("    \t\t\t<div class=\"body\">\r\n");
      out.write("       \t\t\t\t <div class=\"element large first \">\r\n");
      out.write("       \t\t\t\t ");
if(member != null){
      out.write("\r\n");
      out.write("    \t\t\t\t\t    <a href=\"/easyStudy/search.store?gn=GN&userid=");
      out.print(member.getUserId() );
      out.write("\" class=\"image\" style=\"display: block; background-image: url(images/JL/JL0008_01.jpg);\">\r\n");
      out.write("       \t\t\t\t");
}else{ 
      out.write("\t\r\n");
      out.write("       \t\t\t\t   <a href=\"/easyStudy/search.store?gn=GN\" class=\"image\" style=\"display: block; background-image: url(images/JL/JL0008_01.jpg);\">\r\n");
      out.write("       \t\t\t\t");
} 
      out.write("\r\n");
      out.write("       \t\t\t\t\t\t<div class=\"shading\"></div>\r\n");
      out.write("        \t\t\r\n");
      out.write("                    \t\t<div class=\"center\">\r\n");
      out.write("               \t\t\t\t\t<div class=\"middle\">\r\n");
      out.write("                                <div class=\"title\"><h2>GANGNAM</h2></div>\r\n");
      out.write("                                <div class=\"subtitle\"><h1>강남</h1></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("           \t\t\t\t\t</div>\r\n");
      out.write("            \t\t\t</a>\r\n");
      out.write("    \t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"element large\">\r\n");
      out.write("    \t\t\t\t\t<a href=\"/easyStudy/search.store?jl=JL\" class=\"image\" style=\"display: block; background-image: url(images/JL/JL0008_01.jpg);\">\r\n");
      out.write("       \t\t\t\t\t\t<div class=\"shading\"></div>\r\n");
      out.write("        \t\t\r\n");
      out.write("                    \t\t<div class=\"center\">\r\n");
      out.write("               \t\t\t\t\t<div class=\"middle\">\r\n");
      out.write("                                <div class=\"title\"><h2>JONGNO</h2></div>\r\n");
      out.write("                                <div class=\"subtitle\"><h1>종로</h1></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("           \t\t\t\t\t</div>\r\n");
      out.write("            \t\t\t</a>\r\n");
      out.write("    \t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\r\n");
      out.write("    \t\t\t\t<div class=\"element large\">\r\n");
      out.write("    \t\t\t\t\t<a href=\"/easyStudy/search.store?sc=SC\" class=\"image\" style=\"display: block; background-image: url(images/JL/JL0008_01.jpg);\">\r\n");
      out.write("       \t\t\t\t\t\t<div class=\"shading\"></div>\r\n");
      out.write("        \t\t\r\n");
      out.write("                    \t\t<div class=\"center\">\r\n");
      out.write("               \t\t\t\t\t<div class=\"middle\">\r\n");
      out.write("                                <div class=\"title\"><h2>SINCHON</h2></div>\r\n");
      out.write("                                <div class=\"subtitle\"><h1>신촌</h1></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("           \t\t\t\t\t</div>\r\n");
      out.write("            \t\t\t</a>\r\n");
      out.write("    \t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\r\n");
      out.write("   \t\t\t\t</div>\r\n");
      out.write("    \r\n");
      out.write("     \r\n");
      out.write("      \t\t\t<div class=\"title\">종류별</div>\r\n");
      out.write("    \t\t\t<div class=\"body\">\r\n");
      out.write("       \t\t\t\t <div class=\"element large first \">\r\n");
      out.write("    \t\t\t\t\t<a href=\"/easyStudy/search.store?room=S20\" class=\"image\" style=\"display: block; background-image: url(images/JL/JL0008_01.jpg);\">\r\n");
      out.write("       \t\t\t\t\t\t<div class=\"shading\"></div>\r\n");
      out.write("        \t\t\r\n");
      out.write("                    \t\t<div class=\"center\">\r\n");
      out.write("               \t\t\t\t\t<div class=\"middle\">\r\n");
      out.write("                                <div class=\"title\"><h2>ROOM</h2></div>\r\n");
      out.write("                                <div class=\"subtitle\"><h1>스터디룸</h1></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("           \t\t\t\t\t</div>\r\n");
      out.write("            \t\t\t</a>\r\n");
      out.write("    \t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"element large\">\r\n");
      out.write("    \t\t\t\t\t<a href=\"/easyStudy/search.store?cafe=S30\" class=\"image\" style=\"display: block; background-image: url(images/JL/JL0008_01.jpg);\">\r\n");
      out.write("       \t\t\t\t\t\t<div class=\"shading\"></div>\r\n");
      out.write("        \t\t\r\n");
      out.write("                    \t\t<div class=\"center\">\r\n");
      out.write("               \t\t\t\t\t<div class=\"middle\">\r\n");
      out.write("                                <div class=\"title\"><h2>CAFE</h2></div>\r\n");
      out.write("                                <div class=\"subtitle\"><h1>스터디카페</h1></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("           \t\t\t\t\t</div>\r\n");
      out.write("            \t\t\t</a>\r\n");
      out.write("    \t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\r\n");
      out.write("    \t\t\t\t<div class=\"element large\">\r\n");
      out.write("    \t\t\t\t\t<a href=\"/easyStudy/search.store?library=S10\" class=\"image\" style=\"display: block; background-image: url(images/JL/JL0008_01.jpg);\">\r\n");
      out.write("       \t\t\t\t\t\t<div class=\"shading\"></div>\r\n");
      out.write("        \t\t\r\n");
      out.write("                    \t\t<div class=\"center\">\r\n");
      out.write("               \t\t\t\t\t<div class=\"middle\">\r\n");
      out.write("                                <div class=\"title\"><h2>READING ROOM & LIBRARY</h2></div>\r\n");
      out.write("                                <div class=\"subtitle\"><h1>독서실 & 도서관</h1></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("           \t\t\t\t\t</div>\r\n");
      out.write("            \t\t\t</a>\r\n");
      out.write("    \t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\r\n");
      out.write("   \t\t\t\t</div>\r\n");
      out.write("   \t\t\t\t\r\n");
      out.write("\t\t\t</div>\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--쉬운 카테고리 선택 content_warp -->\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"footer_wrap\">\r\n");
      out.write("\t\t<div style=\"width:970px; height:208px; background:gray;\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"main_loginWrap\">\r\n");
      out.write("\t\t<div id=\"main_loginModal\" class=\"main_loginPopup\" style=\"display: none;\">\r\n");
      out.write("\t\t\t<!-- 로그인 페이지-->\r\n");
      out.write("\t\t\t<div id=\"main_login\">\r\n");
      out.write("\t\t\t\t<div id=\"main_loginHeader\">\r\n");
      out.write("\t\t\t\t\t<h1>SEARCH STUDY</h1>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"sel\">\r\n");
      out.write("\t\t\t\t\t<form action=\"login\" method=\"post\" id=\"loginForm\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"main_inputRow\" id=\"main_loginIdArea\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"email\" placeholder=\"이메일\" id=\"main_loginUserId\" name=\"main_loginUserId\" class=\"inputBox1\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"main_labelRow\"  id=\"main_loginIdCheckArea\" style=\"display:none\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"main_loginCheck\" id=\"main_loginIdCheckLabel\"> </label>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"main_inputRow\" id=\"main_passwordArea\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"password\" placeholder=\"비밀번호\" id=\"main_loginUserPwd\" name=\"main_loginUserPwd\" class=\"inputBox1\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"main_labelRow\"  id=\"main_loginPwCheckArea\" style=\"display:none\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"main_loginCheck\" id=\"main_loginPwCheckLabel\"> 패스워드를 다시 확인해주세요</label>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"main_loginBtn_area\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" value=\"로그인\" id=\"main_loginBtn\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"main_sendLoginBtn\" class=\"box\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" id=\"main_login_chk\" value=\"off\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"main_login_chk\">로그인 상태 저장</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div id=\"main_find_info\">\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<!-- <a href=\"#\"> 아이디 찾기</a> <span>|</span> -->\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#main_pwSearchModal\" class=\"main_pwSearchBtn\"> 비밀번호 찾기</a> <span>|</span>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#main_joinModal\" class=\"main_joinPopupBtn\"> 회원가입</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"main_joinModal\" class=\"main_joinPopup\" style=\"display: none;\">\r\n");
      out.write("\t\t\t<!-- 회원가입 페이지-->\r\n");
      out.write("\t\t\t<div id=\"main_join\" >\r\n");
      out.write("\t\t\t\t<div id=\"main_joinHeader\">\r\n");
      out.write("\t\t\t\t\t<h1>SEARCH STUDY</h1>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<form action=\"mjoin\" method=\"post\" id=\"joinForm\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"main_joinIdArea\" class=\"divBox1\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"email\" placeholder=\"이메일\" class=\"inputBox1\" name=\"main_joinUserId\" id=\"main_joinUserId\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"main_labelRow\"  id=\"main_joinIdCheckArea\" style=\"display:none\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"main_loginCheck\" id=\"main_joinIdCheckLabel\"> </label>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"main_joinPwArea\" class=\"divBox1\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"password\" placeholder=\"비밀번호\" class=\"inputBox1\" name=\"main_joinUserPwd\" id=\"main_joinUserPwd\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"main_labelRow\"  id=\"main_joinPwCheckArea\" style=\"display:none\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"main_loginCheck\" id=\"main_joinPwCheckLabel\"> </label>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"main_joinPwcheckArea\" class=\"divBox1\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"password\" placeholder=\"비밀번호확인\" class=\"inputBox1\" name=\"main_joinUserPwdChk\" id=\"main_joinUserPwdChk\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"main_labelRow\"  id=\"main_joinPwCheckChkArea\" style=\"display:none\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"main_loginCheck\" id=\"main_joinPwCheckChkLabel\"> </label>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"main_joinNickArea\" class=\"divBox1\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" placeholder=\"닉네임\" class=\"inputBox1\" name=\"main_joinUserNickName\" id=\"main_joinUserNickName\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"main_labelRow\"  id=\"main_joinNickCheckArea\" style=\"display:none\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"main_loginCheck\" id=\"main_joinNickCheckLabel\"> </label>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"main_sendInfoBtn\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" value=\"가입하기\" id=\"main_joinBtn\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"main_backArea\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#main_loginModal\" class=\"main_loginPopupBtn\"> 로그인</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"main_pwSearchModal\" class=\"main_pwSearchPopup\" style=\"display: none;\">\r\n");
      out.write("\t\t\t<!-- 비밀번호찾기 페이지-->\r\n");
      out.write("\t\t\t<div id=\"main_pwSearch\" >\r\n");
      out.write("\t\t\t\t<div id=\"main_pwSearchHeader\">\r\n");
      out.write("\t\t\t\t\t<h1>SEARCH STUDY</h1>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<form action=\"sendEmail\" method=\"post\" id=\"pwSearchForm\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"main_pwSearchArea\" class=\"divBox1\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" placeholder=\"이메일\" class=\"inputBox1\" name=\"main_pwSearchUser\" id=\"main_pwSearchUser\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"main_labelRow\"  id=\"main_pwSearchCheckArea\" style=\"display:none\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"main_loginCheck\" id=\"main_pwSearchCheckLabel\"> </label>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"main_sendEamilBtn\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" value=\"이메일로 보내기\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"main_backArea\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#main_loginModal\" class=\"main_loginPopupBtn\"> 로그인</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
